
-- ELIMINAR CATEGORÍA
CREATE   PROCEDURE EliminarCategoria
    @Id AS UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION
        DELETE FROM dbo.Categorias WHERE id = @Id;
    COMMIT TRANSACTION;

    SELECT @Id;
END