
-- ELIMINAR UBICACIÓN
CREATE   PROCEDURE EliminarUbicacion
    @Id AS UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION
        DELETE FROM dbo.Ubicaciones WHERE id = @Id;
    COMMIT TRANSACTION;

    SELECT @Id;
END