<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autorizacion.Abstracciones" Version="2.0.5" />
    <PackageReference Include="Autorizacion.Middleware" Version="2.0.5" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.30" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstracciones\Abstracciones.csproj" />
    <ProjectReference Include="..\Autorizacion.Middleware\Autorizacion.Middleware.csproj" />
    <ProjectReference Include="..\DA\DA.csproj" />
    <ProjectReference Include="..\Flujo\Flujo.csproj" />
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
    <ProjectReference Include="..\Reglas\Reglas.csproj" />
  </ItemGroup>

</Project>
